function data = import_xls(workbookFile, sheetName, range)
%IMPORT_XLS Import data from a spreadsheet
%   DATA = IMPORT_XLS(FILE) reads all numeric data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the
%   numeric data.
%
%   DATA = IMPORT_XLS(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORT_XLS(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.
%
%	Non-numeric cells are replaced with: NaN
%
% Windows Example:
%   P7_14d01000 = import_xls('P7_14d01000.xlsx','Sheet1','A2:B411467');
%   P7_14d01000 = import_xls('\BurstsDataExamples\P7_14d01000.xlsx','Sheet1');
%   P7_15116000 = import_xls('\BurstsDataExamples\P7_15116000.xlsx');
%   P7_15911002 = import_xls('\BurstsDataExamples\P7_15911002.xlsx');
%   P18_14n04000 = import_xls('\BurstsDataExamples\P18_14n04000.xlsx');
%   P18_14n25000 = import_xls('\BurstsDataExamples\P18_14n25000.xlsx');
%   P18_14o27005 = import_xls('\BurstsDataExamples\P18_14o27005.xlsx');
% Mac Example:
%   P7_14d01000 = import_xls('BurstsDataExamples/P7_14d01000.xlsx');
%   P7_15116000 = import_xls('BurstsDataExamples/P7_15116000.xlsx');
%   P7_15911002 = import_xls('BurstsDataExamples/P7_15911002.xlsx');
%   P18_14n04000 = import_xls('BurstsDataExamples/P18_14n04000.xlsx');
%   P18_14n25000 = import_xls('BurstsDataExamples/P18_14n25000.xlsx');
%   P18_14o27005 = import_xls('BurstsDataExamples/P18_14o27005.xlsx');
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/02/05 11:44:37

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, range);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));
data = data (2:end,:); % Wenjie: discard first header row (which was replaced by NaN upon import)

